### ISSUE TITLE
who is Justyna Xxx

### ISSUE THREAD

**Issue by rvosa** [naturalis/brassica-snps#8]
...from a Max Planck Institute?

**Comment by fredericlens** [comment]
Justyna is the postdoc from Salma. Salma said during our last meeting that she would contact her. A day later, she emailed me that her postdoc -who is a specialist in flowering genes - is willing to look at the results to look for genes involved in flowering time (cf Eric Schranz). 
Perhaps the mss is going to a different direction, but it could be worthwhile that someone looks at the SNPs in the coding regions of the genes between the bulks? The data is there... Just a thought...
